spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Pet Owner Service
        - id: pet-owner-service
          uri: https://pawfect-pet-owner-service.azurewebsites.net
          predicates:
            - Path=/pet-owner-service/**
          filters:
            - StripPrefix=1

        # Pet Service
        - id: pet-service
          uri: https://pawfect-pet-service.azurewebsites.net
          predicates:
            - Path=/pet-service/**
          filters:
            - StripPrefix=1

        # Veterinary Service
        - id: veterinary-service
          uri: https://pawfect-veterinary-service.azurewebsites.net
          predicates:
            - Path=/veterinary-service/**
          filters:
            - StripPrefix=1

        # Schedule Service
        - id: schedule-service
          uri: https://pawfect-schedule-service.azurewebsites.net
          predicates:
            - Path=/schedule-service/**
          filters:
            - StripPrefix=1

        # Medical Record Service
        - id: medical-record-service
          uri: https://pawfect-medical-record-service.azurewebsites.net
          predicates:
            - Path=/medical-record-service/**
          filters:
            - StripPrefix=1

        # Appointment Service
        - id: appointment-service
          uri: https://pawfect-appointment-service.azurewebsites.net
          predicates:
            - Path=/appointment-service/**
          filters:
            - StripPrefix=1

        # Review Service
        - id: review-service
          uri: https://pawfect-review-service.azurewebsites.net
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1

        # Diagnostic Service
        - id: diagnostic-service
          uri: https://pawfect-diagnostic-service.azurewebsites.net
          predicates:
            - Path=/diagnostic-service/**
          filters:
            - StripPrefix=1

        # IAM Service
        - id: iam-service
          uri: https://pawfect-iam-service.azurewebsites.net
          predicates:
            - Path=/iam-service/**
          filters:
            - StripPrefix=1

        # IAM Service - registro admin
        - id: iam-service-admin-registro
          uri: https://pawfect-iam-service.azurewebsites.net
          predicates:
            - Path=/api/v1/users_admin/registro
          filters:
            - StripPrefix=0

server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://pawfect-registry-service.azurewebsites.net/eureka/}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Pet Owner Service
        url: /pet-owner-service/v3/api-docs
      - name: Pet Service
        url: /pet-service/v3/api-docs
      - name: Veterinary Service
        url: /veterinary-service/v3/api-docs
      - name: IAM Service
        url: /iam-service/v3/api-docs
      - name: Medical Record Service
        url: /medical-record-service/v3/api-docs
      - name: Appointment Service
        url: /appointment-service/v3/api-docs
      - name: Review Service
        url: /review-service/v3/api-docs
      - name: Diagnostic Service
        url: /diagnostic-service/v3/api-docs
      - name: Schedule Service
        url: /schedule-service/v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
